#!/usr/bin/env bash
# Stage and push a Send Invites trigger in one command.
#
# Usage:
#   ./stage_send.sh pilot   https://us.onetimesecret.com/secret/<KEY>
#   ./stage_send.sh batch1  https://us.onetimesecret.com/secret/<KEY>   # local run only — see below
#   ./stage_send.sh batch2  https://us.onetimesecret.com/secret/<KEY>   # local run only — see below
#
# Modes:
#   pilot    → 6 test addresses in mailer/recipients.txt (PUBLIC, in the
#              repo). Writes the trigger file, commits, prints the push
#              command. Works on GitHub Actions.
#
#   batch1 / batch2 → 400 / 398 real alumni addresses in the gitignored
#              recipients_batch{1,2}.local.txt. The Actions runner cannot
#              see those files (gitignored ≠ in checkout), so this script
#              instead prints the LOCAL command to run on a machine with
#              open SMTP (port 465).
#
# This script never echoes the OTS URL, never commits the URL outside the
# trigger file, and never copies PII into a tracked file.
set -euo pipefail

BATCH="${1:-}"
URL="${2:-}"
if [ -z "$BATCH" ] || [ -z "$URL" ]; then
  echo "Usage: $0 <pilot|batch1|batch2> <onetimesecret_url>" >&2
  exit 2
fi

if ! echo "$URL" | grep -qE '^https://[a-z0-9.-]+\.onetimesecret\.[a-z]+/secret/[A-Za-z0-9]+$'; then
  echo "URL does not look like a one-time-secret link." >&2
  exit 2
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
TEMPLATE="INVITATION EMAIL/campaigns/programadores-cariocas-survey/invite_body.txt"
FROM_NAME="Equipe Programadores Cariocas"

case "$BATCH" in
  pilot)
    TRIGGER="$SCRIPT_DIR/pending-send.url"
    {
      echo "# Auto-generated by stage_send.sh — pilot send for prog-cariocas survey."
      echo "url=$URL"
      echo "template=$TEMPLATE"
      echo "from_name=$FROM_NAME"
    } > "$TRIGGER"
    echo "Trigger file written: $TRIGGER"
    echo ""
    echo "Next:"
    echo "  cd $REPO_ROOT"
    echo "  git add -- 'INVITATION EMAIL/mailer/pending-send.url'"
    echo "  git commit -m 'send-invites: trigger pilot — prog-cariocas survey'"
    echo "  git push"
    ;;
  batch1|batch2)
    RECIPIENTS="INVITATION EMAIL/campaigns/programadores-cariocas-survey/recipients_${BATCH}.local.txt"
    if [ ! -f "$REPO_ROOT/$RECIPIENTS" ]; then
      echo "Recipients file missing: $REPO_ROOT/$RECIPIENTS" >&2
      echo "These are PII and gitignored; they live on Otávio's machine only." >&2
      exit 1
    fi
    echo "Run this on your machine (has SMTP open — Actions runners are fine too,"
    echo "but the recipients file is gitignored, so CI cannot see it):"
    echo ""
    echo "  cd '$REPO_ROOT'"
    echo "  python3 'INVITATION EMAIL/mailer/retrieve_and_send.py' \\"
    echo "    --recipients '$RECIPIENTS' \\"
    echo "    --template   '$TEMPLATE' \\"
    echo "    --from-name  '$FROM_NAME' \\"
    echo "    '$URL'"
    ;;
  *)
    echo "Unknown batch: $BATCH (use: pilot, batch1, batch2)" >&2
    exit 2
    ;;
esac
